/*
-----------------------------------------
File: CartStyles.js

Purpose:
Styles for the Cart screen preserving the blue & white ICH theme.
-----------------------------------------
*/

import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#005BAC',
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  header: {
    backgroundColor: '#005BAC', // Signature Blue header
    paddingTop: 48,
    paddingBottom: 16,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 4,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.12,
    shadowRadius: 6,
    zIndex: 10,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backIcon: {
    width: 20,
    height: 20,
    tintColor: '#FFFFFF',
  },
  headerTitle: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
    marginHorizontal: 12,
    textAlign: 'center',
  },
  deleteCartIcon: {
    width: 22,
    height: 22,
    tintColor: '#FFFFFF',
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 140, // Space for sticky bottom bar & summary
  },
  itemCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E4E9F0',
    shadowColor: '#102A43',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  itemImage: {
    width: 80,
    height: 80,
    borderRadius: 14,
    backgroundColor: '#F0F4F8',
  },
  itemContent: {
    flex: 1,
    marginLeft: 12,
    justify: 'space-between',
    minHeight: 80,
  },
  itemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemName: {
    flex: 1,
    color: '#102A43',
    fontSize: 16,
    fontWeight: '800',
    marginRight: 8,
  },
  itemTotalPrice: {
    color: '#102A43',
    fontSize: 16,
    fontWeight: '900',
  },
  itemDescription: {
    color: '#627D98',
    fontSize: 12,
    marginTop: 2,
    marginBottom: 6,
  },
  itemBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemUnitPrice: {
    color: '#005BAC',
    fontSize: 13,
    fontWeight: '700',
  },
  quantitySelector: {
    height: 32,
    minWidth: 92,
    borderRadius: 16,
    backgroundColor: '#F9A826', // Orange quantity selector in Cart
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  quantityBtn: {
    width: 30,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityBtnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 20,
  },
  quantityText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
    paddingHorizontal: 2,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginTop: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E4E9F0',
    shadowColor: '#102A43',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  summaryTitle: {
    color: '#102A43',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F8',
    paddingBottom: 8,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  summaryLabel: {
    color: '#627D98',
    fontSize: 14,
    fontWeight: '600',
  },
  summaryValue: {
    color: '#102A43',
    fontSize: 14,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: '#E4E9F0',
    marginVertical: 10,
  },
  grandTotalLabel: {
    color: '#102A43',
    fontSize: 16,
    fontWeight: '800',
  },
  grandTotalValue: {
    color: '#005BAC',
    fontSize: 20,
    fontWeight: '900',
  },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  emptyIllustrationWrapper: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#EBF4FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 2,
    borderColor: '#BEE3F8',
  },
  emptyIcon: {
    width: 52,
    height: 52,
    tintColor: '#005BAC',
  },
  emptyTitle: {
    color: '#102A43',
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 8,
  },
  emptySubtitle: {
    color: '#627D98',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  continueButton: {
    height: 48,
    paddingHorizontal: 28,
    borderRadius: 24,
    backgroundColor: '#005BAC',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#005BAC',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  continueButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 12,
    shadowColor: '#102A43',
    shadowOffset: {width: 0, height: -6},
    shadowOpacity: 0.12,
    shadowRadius: 16,
    borderTopWidth: 1,
    borderColor: '#E4E9F0',
  },
  bottomLeft: {
    flexDirection: 'column',
  },
  bottomTotalLabel: {
    color: '#627D98',
    fontSize: 12,
    fontWeight: '700',
  },
  bottomTotalPrice: {
    color: '#102A43',
    fontSize: 22,
    fontWeight: '900',
  },
  checkoutButton: {
    height: 46,
    paddingHorizontal: 26,
    borderRadius: 23,
    backgroundColor: '#F9A826', // Vibrant Orange CTA button
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#F9A826',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  checkoutButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
});

export default styles;
