import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: '#F5F7FA'},
  header: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, backgroundColor: '#1565C0'},
  headerTitle: {color: '#FFFFFF', fontSize: 22, fontWeight: '700'},
  headerButton: {width: 44, height: 44, alignItems: 'center', justifyContent: 'center'},
  backIcon: {width: 24, height: 24, tintColor: '#FFFFFF'},
  headerEditIcon: {width: 22, height: 22, tintColor: '#FFFFFF'},
  content: {padding: 16, paddingBottom: 28, backgroundColor: '#F5F7FA'},
  profileCard: {alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 18, backgroundColor: '#FFFFFF', padding: 24, shadowColor: '#102A43', shadowOffset: {width: 0, height: 5}, shadowOpacity: 0.06, shadowRadius: 12, elevation: 3},
  avatar: {width: 88, height: 88, borderRadius: 44, alignItems: 'center', justifyContent: 'center', backgroundColor: '#EAF4FF', borderWidth: 3, borderColor: '#B9DDF8'},
  avatarText: {color: '#005BAC', fontSize: 30, fontWeight: '800'},
  name: {marginTop: 14, color: '#1E293B', fontSize: 22, fontWeight: '800'},
  employeeId: {marginTop: 4, color: '#64748B', fontSize: 14, fontWeight: '600'},
  contactRow: {flexDirection: 'row', alignItems: 'center', marginTop: 14},
  contactText: {color: '#475569', fontSize: 14},
  detailsCard: {marginTop: 16, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 18, backgroundColor: '#FFFFFF', paddingHorizontal: 16, shadowColor: '#102A43', shadowOffset: {width: 0, height: 5}, shadowOpacity: 0.05, shadowRadius: 10, elevation: 2},
  sectionTitle: {paddingTop: 18, paddingBottom: 8, color: '#1E293B', fontSize: 17, fontWeight: '800'},
  detailRow: {flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#EEF2F6'},
  lastDetailRow: {borderBottomWidth: 0},
  detailLabel: {color: '#64748B', fontSize: 14},
  detailValue: {color: '#1E293B', fontSize: 14, fontWeight: '700'},
  actionRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 16, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 14, backgroundColor: '#FFFFFF', paddingHorizontal: 16, paddingVertical: 17},
  mobileActionIcon: {width: 20, height: 20},
  logoutContent: {flexDirection: 'row', alignItems: 'center'},
  logoutIcon: {width: 22, height: 22, marginRight: 10},
  actionText: {color: '#1E293B', fontSize: 16, fontWeight: '700'},
  logoutText: {color: '#DC2626', fontSize: 16, fontWeight: '700'},
  modalBackdrop: {flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: 'rgba(15, 23, 42, 0.45)'},
  modalCard: {width: '100%', maxWidth: 380, borderRadius: 18, backgroundColor: '#FFFFFF', padding: 20},
  modalTitle: {color: '#1E293B', fontSize: 20, fontWeight: '800'},
  inputLabel: {marginTop: 16, marginBottom: 7, color: '#475569', fontSize: 13, fontWeight: '700'},
  input: {height: 46, borderWidth: 1, borderColor: '#CBD5E1', borderRadius: 10, paddingHorizontal: 12, color: '#1E293B', fontSize: 15},
  formError: {marginTop: 10, color: '#DC2626', fontSize: 13},
  modalActions: {flexDirection: 'row', justifyContent: 'flex-end', marginTop: 22},
  cancelButton: {height: 42, paddingHorizontal: 16, alignItems: 'center', justifyContent: 'center'},
  cancelButtonText: {color: '#475569', fontSize: 14, fontWeight: '700'},
  saveButton: {height: 42, marginLeft: 10, paddingHorizontal: 20, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: '#005BAC'},
  saveButtonText: {color: '#FFFFFF', fontSize: 14, fontWeight: '800'},
addressArrow: {
  color: '#005BAC',
  fontSize: 28,
  fontWeight: '600',
},
});

export default styles;
