import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    padding: 12,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E4E9F0',
    shadowColor: '#102A43',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  cardPressed: {opacity: 0.94},
  imageWrap: {width: 102, height: 102, borderRadius: 14, overflow: 'hidden'},
  image: {width: '100%', height: '100%', backgroundColor: '#EAF1F8'},
  content: {flex: 1, minHeight: 102, marginLeft: 13, justifyContent: 'space-between'},
  titleRow: {flexDirection: 'row', alignItems: 'center'},
  name: {flex: 1, marginLeft: 7, color: '#102A43', fontSize: 16, fontWeight: '800'},
  description: {marginTop: 4, color: '#627D98', fontSize: 12, lineHeight: 17},
  vegIcon: {width: 15, height: 15, borderWidth: 1.5, borderColor: '#1E8E3E', borderRadius: 3, alignItems: 'center', justifyContent: 'center'},
  vegDot: {width: 7, height: 7, borderRadius: 4, backgroundColor: '#1E8E3E'},
  nonVegIcon: {borderColor: '#D93025'},
  nonVegDot: {backgroundColor: '#D93025'},
  metaRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 7},
  rating: {color: '#52606D', fontSize: 12, fontWeight: '700'},
  price: {color: '#005BAC', fontSize: 16, fontWeight: '900'},
  addButton: {height: 34, minWidth: 90, marginTop: 9, borderRadius: 17, backgroundColor: '#F9A826', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16},
  addButtonText: {color: '#FFFFFF', fontSize: 13, fontWeight: '900', letterSpacing: 0.4},
  quantitySelector: {minWidth: 120, height: 34, marginTop: 9, borderRadius: 17, backgroundColor: '#005BAC', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', overflow: 'hidden', paddingHorizontal: 4},
  quantityButton: {width: 40, height: '100%', alignItems: 'center', justifyContent: 'center'},
  quantityButtonText: {color: '#FFFFFF', fontSize: 20, fontWeight: '900', lineHeight: 22},
  quantityText: {minWidth: 26, textAlign: 'center', color: '#FFFFFF', fontSize: 14, fontWeight: '900'},
});
