import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  screen: {flex: 1, backgroundColor: '#F5F7FA'},
  header: {paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#1565C0'},
  headerButton: {width: 44, height: 44, alignItems: 'center', justifyContent: 'center'},
  backIcon: {width: 24, height: 24, tintColor: '#FFFFFF'},
  headerTitle: {color: '#FFFFFF', fontSize: 22, fontWeight: '700'},
  downloadButton: {width: 44, height: 44, alignItems: 'center', justifyContent: 'center'},
  downloadIcon: {width: 22, height: 22},
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F7FA',
    padding: 24,
  },
  listContent: {
    padding: 16,
    paddingBottom: 28,
    backgroundColor: '#F5F7FA',
  },
  billCard: {
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 16,
    shadowColor: '#102A43',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  selectedCard: {borderColor: '#005BAC', borderWidth: 1.5},
  cardHeader: {flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between'},
  billId: {color: '#005BAC', fontSize: 16, fontWeight: '800'},
  orderId: {marginTop: 4, color: '#64748B', fontSize: 12, fontWeight: '600'},
  date: {maxWidth: 128, color: '#64748B', fontSize: 11, lineHeight: 16, textAlign: 'right'},
  divider: {height: 1, marginVertical: 13, backgroundColor: '#EEF2F6'},
  itemRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8},
  itemName: {flex: 1, paddingRight: 12, color: '#334155', fontSize: 14},
  itemQuantity: {color: '#64748B', fontSize: 14, fontWeight: '700'},
  totalRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 7, paddingTop: 12, borderTopWidth: 1, borderTopColor: '#EEF2F6'},
  totalLabel: {color: '#475569', fontSize: 14, fontWeight: '700'},
  paymentStatus: {marginTop: 3, color: '#16A34A', fontSize: 12, fontWeight: '700'},
  totalValue: {color: '#1E293B', fontSize: 17, fontWeight: '800'},
  emptyState: {
    width: '88%',
    maxWidth: 320,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    paddingVertical: 28,
    paddingHorizontal: 24,
    shadowColor: '#102A43',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  emptyIcon: {
    width: 90,
    height: 90,
  },
  title: {
    marginTop: 16,
    color: '#1E293B',
    fontSize: 19,
    fontWeight: '800',
  },
  subtitle: {
    marginTop: 8,
    color: '#64748B',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
});

export default styles;
